CREATE TABLE seats (
  id INT NOT NULL AUTO_INCREMENT, 
  seats JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

ALTER TABLE seats ADD CONSTRAINT pk_seats PRIMARY KEY (id);
